name: Test Workflow

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout trigger branch
        uses: actions/checkout@v3

      - name: Attempt rebase
        run: |
          git fetch 
          git rebase

      - name: Setup-java
        uses: actions/setup-java@v3
        with:
          distribution: semeru
          java-version: 17

      - name: Run SQL script
        run: |
          mysql --host 127.0.0.1 --port 3306 --user root --password=root < SQL/testDatabase/1-create-test-database.sql
          mysql --host 127.0.0.1 --port 3306 --user root --password=root projectcalculationtool_test_db < SQL/testDatabase/2-insert-test-data.sql

      - name: Show Database
        run: mysqlshow --host 127.0.0.1 --port 3306 --user root --password=root projectcalculationtool_test_db

      - name: Build with Maven
        run: |
          chmod +x mvnw
          ./mvnw -Dspring.profiles.active=test clean package

      - name: Push changes to main
        run: git push --force-with-lease origin ${{ github.ref }}:main